# Generated by Django 4.1.7 on 2023-03-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
    ]
