# Generated by Django 4.1.7 on 2023-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
